Repository MatthewHunt84/MetaCocktailsSwiftData, pull requests merged in 2024-09, with the labels that each got.

#154 Added keyboard done button
  MetaCocktailsSwiftData/Views/Search View/Ingredient Search View/IngredientSearchView.swift
Labels: Ready to merge, Edited by reviewer

#157 Organized minus one list
  MetaCocktailsSwiftData/EntryPoint/FirstLaunchLoadingView.swift
  MetaCocktailsSwiftData/EntryPoint/MetaCocktailsSwiftDataApp.swift
  MetaCocktailsSwiftData/Model/Cocktails/MilkAndHoney/TheMedicinaLatina.swift
  MetaCocktailsSwiftData/Model/Components/Ingredients/NonAlchololicIngredients.swift
  MetaCocktailsSwiftData/Views/Design/FontFactory.swift
  MetaCocktailsSwiftData/Views/Search View/Ingredient Search View/Matched Cocktails Views.swift
  MetaCocktailsSwiftData/Views/Search View/SearchViewModel.swift
  MetaCocktailsSwiftData/Views/Search View/TitleHeaders/Searched Cocktail Title Headers.swift
Labels: Ready to merge, Edited by reviewer

#159 Updated the look of custom alert and Historical cocktail reference modal
  MetaCocktailsSwiftData/Assets.xcassets/Image.imageset/Contents.json
  MetaCocktailsSwiftData/Assets.xcassets/dice.imageset/dice (1).png
  MetaCocktailsSwiftData/Views/Cocktail List View/SubViews/HistoricalCocktailModalView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/AddCocktailView.swift
  MetaCocktailsSwiftData/Views/CustomAlertView/CustomAlertView.swift
  MetaCocktailsSwiftData/Views/Recipe View/RecipeView.swift
Labels: Ready to merge, Edited by reviewer

#163 Alphabet view, but with fonts that grow with device size.
  MetaCocktailsSwiftData/Views/Cocktail List View/CocktailListView.swift
  MetaCocktailsSwiftData/Views/Design/FontFactory.swift
Labels: Ready to merge

#160 Cbc remodel
  MetaCocktailsSwiftData.xcodeproj/project.pbxproj
  MetaCocktailsSwiftData/Assets.xcassets/BlueTintBottle.imageset/BlueTintBottle.png
  MetaCocktailsSwiftData/Assets.xcassets/BlueTintBottle.imageset/Contents.json
  MetaCocktailsSwiftData/Assets.xcassets/White Liquor Bottle.imageset/Contents.json
  MetaCocktailsSwiftData/Assets.xcassets/White Liquor Bottle.imageset/White Liquor Bottle.png
  MetaCocktailsSwiftData/Utilities/Extensions/TextField+Extension.swift
  MetaCocktailsSwiftData/Views/Cocktail List View/SubViews/HistoricalCocktailModalView.swift
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/BatchCellView.swift
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/BottleBatchCell.swift
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/CBCLoadedCocktailView.swift
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/CBCViewModel.swift
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/EditBatchModalView.swift
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/FloatingPromptView.swift
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/MainBatchView.swift
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/Sub Views/BottleMathModalView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/AddCocktailView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/SubViews/AddIngredient/AddedIngredientView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/SubViews/AddIngredient/CustomIngredient/AddCustomIngredientView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/SubViews/AddIngredient/CustomIngredient/CustomIngredientRecipeView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/SubViews/AddIngredient/ExistingIngredient/AddExistingIngredientDetailView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/SubViews/CocktailBuildSteps/AddBuildStepView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/SubViews/Garnish/GarnishDetailView.swift
  MetaCocktailsSwiftData/Views/CustomAlertView/CustomAlertView.swift
  MetaCocktailsSwiftData/Views/Design/ColorScheme.swift
  MetaCocktailsSwiftData/Views/Design/FontFactory.swift
  MetaCocktailsSwiftData/Views/Design/Headers.swift
  MetaCocktailsSwiftData/Views/Loading Indicators/DefaultLoadingIndicator.swift
  MetaCocktailsSwiftData/Views/Search View/Ingredient Search View/IngredientSearchView.swift
  MetaCocktailsSwiftData/Views/Search View/SearchViewModel.swift
  MetaCocktailsSwiftData/Views/Search View/SubViews/DefaultIngredientSearchCell.swift
  MetaCocktailsSwiftData/Views/Search View/SubViews/IncludedIngredientSearchCell.swift
  MetaCocktailsSwiftData/Views/Search View/TitleHeaders/Searched Cocktail Title Headers.swift
  MetaCocktailsSwiftData/Views/Subviews/Buttons/BackButton.swift
  MetaCocktailsSwiftData/Views/Subviews/Buttons/BatchButton .swift
  MetaCocktailsSwiftData/Views/Subviews/Buttons/ButtonStyles.swift
  MetaCocktailsSwiftData/Views/Subviews/Buttons/XDismissButton.swift
  MetaCocktailsSwiftData/Views/Subviews/Cells/LoadedCocktailIngredientCell.swift
  MetaCocktailsSwiftData/Views/Subviews/CocktailImages/CocktailImageView.swift
Labels: Edited by reviewer

#161 Remodeled SplitBatchView
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/CBCLoadedCocktailView.swift
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/CBCViewModel.swift
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/SplitBatchView.swift
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/Sub Views/ContainerMenuView.swift
  MetaCocktailsSwiftData/Views/Subviews/Cells/SplitBatchCell.swift
Labels: enhancement, Ready to merge, Edited by reviewer

#170 Add cocktail view bug fixes
  MetaCocktailsSwiftData.xcodeproj/project.pbxproj
  MetaCocktailsSwiftData/Model/Components/Build.swift
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/CBCLoadedCocktailView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/AddCocktailView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/AddCocktailViewModel.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/SubViews/AddIngredient/CustomIngredient/AddCustomIngredientView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/SubViews/AddIngredient/CustomIngredient/AddRecipeStepDetailView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/SubViews/AddIngredient/CustomIngredient/CustomIngredientRecipeView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/SubViews/AddIngredient/ExistingIngredient/AddExistingIngredientDetailView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/SubViews/CocktailBuildSteps/AddBuildStepDetailView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/SubViews/CocktailBuildSteps/AddBuildStepView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/SubViews/Garnish/AddCustomGarnishView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/SubViews/Garnish/GarnishDetailView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/SubViews/RiffPickerView.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/SubViews/VariationPicker/VariationPickerDetailView.swift
  MetaCocktailsSwiftData/Views/CustomAlertView/CustomAlertView.swift
  MetaCocktailsSwiftData/Views/Design/FontFactory.swift
  MetaCocktailsSwiftData/Views/Design/UniversalBlueButton.swift
  MetaCocktailsSwiftData/Views/Recipe View/RecipeView.swift
Labels: Ready to merge

#174 CBC Bug Fixes
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/BatchCellView.swift
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/CBCLoadedCocktailView.swift
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/CBCViewModel.swift
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/EditBatchModalView.swift
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/SplitBatchView.swift
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/Sub Views/BottleMathModalView.swift
  MetaCocktailsSwiftData/Views/CocktailBatchingCalculator/Sub Views/ContainerMenuView.swift
Labels: Ready to merge

#172 Recipe view bug fixes
  MetaCocktailsSwiftData.xcodeproj/project.pbxproj
  MetaCocktailsSwiftData/Animations/AnimationModifiers.swift
  MetaCocktailsSwiftData/Views/Design/FontFactory.swift
  MetaCocktailsSwiftData/Views/Design/Headers.swift
  MetaCocktailsSwiftData/Views/Recipe View/RecipeFlipCardView.swift
  MetaCocktailsSwiftData/Views/Recipe View/RecipeView.swift
  MetaCocktailsSwiftData/Views/Recipe View/RecipeViewModel.swift
  MetaCocktailsSwiftData/Views/Recipe View/SwipeRecipeView.swift
Labels: Ready to merge

#182 Removed .onAppear modifier that was clearing ingredientName
  MetaCocktailsSwiftData/Views/CreateACocktailView/AddCocktailViewModel.swift
  MetaCocktailsSwiftData/Views/CreateACocktailView/SubViews/AddIngredient/ExistingIngredient/AddExistingIngredientDetailView.swift
Labels: Ready to merge

#181 Fixed initial cocktail navigation from disclosure group
  MetaCocktailsSwiftData/Views/Recipe View/RecipeFrontView.swift
Labels: Ready to merge
